WORLD_NAME:                           "reInvent2019_track"
SAGEMAKER_SHARED_S3_BUCKET:           "sagemaker-us-west-2-325941545516"
SAGEMAKER_SHARED_S3_PREFIX:           "deepracer-notebook-sagemaker-200221-161910"
TRAINING_JOB_ARN:                     "arn:aws:sagemaker:us-west-2:325941545516:training-job/deepracer-notebook-2020-02-21-16-21-32-103"
METRICS_S3_BUCKET:                    "sagemaker-us-west-2-325941545516"
METRICS_S3_OBJECT_KEY:                "deepracer-notebook-sagemaker-200221-161910/training_metrics.json"
AWS_REGION:                           "us-west-2"
TARGET_REWARD_SCORE:                  "None"
NUMBER_OF_EPISODES:                   "0"
ROBOMAKER_SIMULATION_JOB_ACCOUNT_ID:  "325941545516"
JOB_TYPE:                             "TRAINING"
CHANGE_START_POSITION:                "true"
ALTERNATE_DRIVING_DIRECTION:          "false"
KINESIS_VIDEO_STREAM_NAME:            "dr-kvs-deepracer-notebook-2020-02-21-16-21-32-103"
REWARD_FILE_S3_KEY:                   "deepracer-notebook-sagemaker-200221-161910/customer_reward_function.py"
MODEL_METADATA_FILE_S3_KEY:           "deepracer-notebook-sagemaker-200221-161910/model/model_metadata.json"
NUMBER_OF_OBSTACLES:                  "0"
MIN_DISTANCE_BETWEEN_OBSTACLES:       "2.0"
RANDOMIZE_OBSTACLE_LOCATIONS:         "false"
PSEUDO_RANDOMIZE_OBSTACLE_LOCATIONS:  "false"
NUMBER_OF_PSEUDO_RANDOM_PLACEMENTS:   "2"
IS_OBSTACLE_BOT_CAR:                  "false"
IS_LANE_CHANGE:                       "false"
LOWER_LANE_CHANGE_TIME:               "3.0"
UPPER_LANE_CHANGE_TIME:               "5.0"
LANE_CHANGE_DISTANCE:                 "1.0"
NUMBER_OF_BOT_CARS:                   "6"
MIN_DISTANCE_BETWEEN_BOT_CARS:        "2.0"
RANDOMIZE_BOT_CAR_LOCATIONS:          "false"
BOT_CAR_SPEED:                        "0.2"
CAR_COLOR:                            "LightBlue"
FIRST_PERSON_VIEW:                    "false"
CHANGE_START_POSITION:                "true"
